name: multitask
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

repository: https://github.com/schlimmsten/multitask

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_material_color_picker: ^1.2.0
  shared_preferences: ^2.2.3
  flutter_slidable: ^3.1.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  flutter_local_notifications: ^17.1.2
  flutter_timezone: ^1.0.8
  rxdart: ^0.27.7
  timezone: ^0.9.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^1.1.0
  build_runner: ^2.0.4
  analyzer: ^4.7.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/MT_blue_for_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "images/MT_blue_for_icon.png"
  windows:
    generate: true
    image_path: "images/MT_blue_for_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "images/MT_blue_for_icon.png"
flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
  assets:
    - images/

platforms:
  android:
  ios: